### ISSUE TITLE
nix-script fails

### ISSUE THREAD

**Issue by rnhmjoj** [bennofs/nix-script#1]
Scripts fail to run and nix-script prints an error. With you example code:

```
nix-script: #!> haskell
#! haskell | text lens optparse-applica: openFile: does not exist (No such file or directory)
```

**Comment by bennofs** [comment]
Hmm, this might caused by the haskell updates in Nixpkgs / Nixos Unstable. I pushed d28f2a, can you test if that example works?

**Comment by rnhmjoj** [comment]
Yes! It works now. Thank you.
